### ISSUE TITLE
Support config-file-validator v1.6.0

### ISSUE THREAD

**Issue by kehoecj** [kehoecj/validate-configs-action#5]

**Comment by hype8912** [comment]
Any plans on completing this issue? v2 targeting 1.5.0 doesn't seem to work or gets syntax errors when I try to use it.

**Comment by kehoecj** [comment]
@hype8912 I'll see about adding support today - although v2 targeting 1.5.0 should work. Just curious what syntax errors do you see?

**Comment by kehoecj** [comment]
@hype8912 Done - I think I saw the issue you were running into as well in v2. Let me know if this release is now working for you

**Comment by hype8912** [comment]
It worked the first time I ran it like below:

```
jobs:
  ini-lint:
    name: 'ini-lint'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4

      - name: 'Config file validator'
        uses: kehoecj/validate-configs-action@v3
```

I'm running on my own runners and not on GitHub. Looking into it more it runs good on the windows 10 machine running inside of docker desktop but it fails on the raspberry pi machine running it inside of docker. Below is the error message. I'm guessing whatever "ubuntu-latest" image my build is pulling to use is missing a dependency when running on the raspberry pi docker instance. I'll let you know more if I figure out anything more.

```
/usr/local/bin/validator: line 1: syntax error: unexpected "("
```

Thank you for updating the version.
